##### APPLICATION SETTING PROPERTIES #####
## APP ENV DELIMITER ##
app.env.delimiter=:

## LOGOUT ##
logout.success.url=/web/Home

## LOGGER ##
# 0 for Disable And 1 for Enable #
app.logger.enable=1
#log.file.dir=/mcslogs/sdmc/master/
log.file.dir=D:/
#log.file.name=MASTER-LOG

## CAPTCHA ##
# 0 for Disable And 1 for Enable #
captcha.enable=0

## LOGIN PROPERTIES ##
## -- 1 means enable & 0 means disable ##
login.db.enable=1

## LDAP PROPERTIES ##
## -- 1 means enable & 0 means disable ##
login.ldap.enable=0

ldap.url=ldaps://auths.nic.in
ldap.bindDN=uid=mcdsuite-ldp.auth,ou=People,o=inoc services,o=Application Services,o=nic.in,dc=nic,dc=in
ldap.bindPass=as@$TY123
ldap.baseDN=ou=People,o=eastdmc.nic.in,o=Paid accounts,o=nic.in,dc=nic,dc=in 

## PARICHAY PROPERTIES ##
## -- 1 means enable & 0 means disable ##
parichay.enable=0

#parichay.serviceName=SDMCMST
#parichay.serviceAPIKey=zx2DQLPs5DZglDU1+scs1Zmg6CRBRLaD
#parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=SDMCMST

#parichay.serviceName=NDMCMST
#parichay.serviceAPIKey=5P8h1ad1wRtc56NooMEN5QY9UrGOpvGs
#parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=NDMCMST

########################TEST################################################

#parichay.serviceName=SDMCMST
#parichay.serviceAPIKey=q16OTiKzkRCA5Z6Cr9QDkxo82SDcm6f8
#parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=SDMCMST

#parichay.serviceName=NDMCMST
#parichay.serviceAPIKey=j9SEo7D9RHx3aWuYQe3km072eYy6v221
#parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=NDMCMST

#parichay.serviceName=EDMCMST
#parichay.serviceAPIKey=49Cvnm7UB1pQAt92GTySJujygCmqR1TS
#parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=EDMCMST

########################LIVE################################################

#parichay.serviceName=SDMCMST
#parichay.serviceAPIKey=zx2DQLPs5DZglDU1+scs1Zmg6CRBRLaD
#parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=SDMCMST

#parichay.serviceName=NDMCMST
#parichay.serviceAPIKey=5P8h1ad1wRtc56NooMEN5QY9UrGOpvGs
#parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=NDMCMST

#parichay.serviceName=EDMCMST
#parichay.serviceAPIKey=D1L72sTkooci85Q9XoKaOACYV0nmQnPY
#parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=EDMCMST



parichay.serviceName=EDMCMST
parichay.serviceAPIKey=D1L72sTkooci85Q9XoKaOACYV0nmQnPY
parichay.client.timeout=https://parichay.nic.in/Accounts/ClientManagement?sessionTimeOut=true&service=EDMCMST

parichay.login=https://parichay.nic.in/Accounts/Services
parichay.token.valid=https://parichay.nic.in:8081/Accounts/openam/login/isTokenValid
parichay.client.token.validator=https://parichay.nic.in/Accounts/openam/login/validateClientToken
parichay.client.timeout.api=https://parichay.nic.in:8081/Accounts/openam/login/clientSessionTimeout
parichay.logout=https://parichay.nic.in/Accounts/openam/login/logoutAll

## SESSION TIME OUT ##
session.timeout=10



##### Jan Parichay Properteis 
jan.parichay.enable=0
jan.prichay.service  = ptrlnmhspuh7m57yjwz1wc0xokv3mr3c
jan.prichay.hmac_url = http://10.197.214.9:8080/hmac
jan.prichay.encr_url = http://10.197.214.9:8080/encryption
jan.prichay.handshaking_url = http://10.197.214.9:8080/handshake
jan.prichay.dec_url =http://10.197.214.9:8080/decryption
jan.prichay.logout_url = http://10.197.214.9:8080/logoutAll
jan.prichay.token_validate = http://10.197.214.9:8080/isTokenValid
jan.prichay.sess_timeout = http://10.197.214.9:8080/timeout
jan.prichay.parichay_url =https://janparichaystag.meripehchaan.gov.in

