#### CONCAT STRING DELIMITER ###
#concat.string.delimiter=:
#
#role.code.system.HTL=HTL_MHO
##role.code.system.admin=ADMM
##role.code.system.admin=SYSADM
#role.code.system.app_masters=APPLICATION_MASTERS
#
#role.code.system.menu.role.common_master=COMMON_MASTER
#role.code.system.menu.role.property_master=PROPERTY_MASTER
#role.code.system.menu.role.factory_master=FACTORY_MASTER
#role.code.system.menu.role.citizen_master=CITIZEN_MASTER
#role.code.system.menu.role.citizen_master.admin=CITIZEN_ADMIN_MASTER
#
#role.code.system.menu.role.mchallan_master=MCHALLAN_MASTER
#role.code.system.menu.role.health_master=HEALTH_MASTER
#role.code.system.menu.role.rbd_master=RBD_MASTER
##role.code.system.menu.role.cremBurial_master=CREMBURIAL_MASTER
#role.code.system.menu.role.payment_master=PAYMENT_MASTER
#role.code.system.menu.role.alerts_master=ALERTS_MASTER
#role.code.system.menu.role.gtl_master=GTL_MASTER
#role.code.system.menu.role.vtl_master=VTL_MASTER
#role.code.system.menu.role.tehbazari_master=TEHBAZARI_MASTER
#role.code.system.menu.role.csd_master=CSD_MASTER
#role.code.system.menu.role.bkubk_master=BKUBK_MASTER
#role.code.system.menu.role.eodb_masters=EODB_MASTERS
#role.code.system.menu.role.usercharge_masters=USERCHARGE_MASTERS
#role.code.system.menu.role.adms_masters=ADMS_MASTERS
#role.code.system.menu.role.ruleEngine_masters=RULEENGINE_MASTERS
#role.code.system.menu.role.lems_masters=LEMS_MASTERS
#role.code.system.menu.role.prms_masters=PRMS_MASTERS
#role.code.system.menu.role.signage_masters=SIGNAGE_MASTERS
##Hotel Motel
#role.code.system.menu.role.hmf_masters=HMF_MASTERS
##role.code.system.menu.role.hospital_master=HOSPITAL_MASTER
#
##role.code.system.admin=PADM
##role.code.system.admin=ADMM
#
#
##### Heading Masters Code ###
#role.code.master.menu.common_master=Common Master
#role.code.master.menu.property_master=Property Master
#role.code.master.menu.property_ref_master=Property Reference Data
#role.code.master.menu.factory_master=Factory Master
#role.code.master.menu.citizen_master=Portal Master
#role.code.master.menu.mchallan_master=MChallan Master
#role.code.master.menu.health_master=HealthTrade Master
#role.code.master.menu.rbd_master=RBD Master
#role.code.master.menu.cremBurial_master=CremBurial Master
#role.code.master.menu.payment_master=Payment Master
#role.code.master.menu.alerts_master=Alerts
#role.code.master.menu.hospital_master=Hospital
#role.code.master.menu.gtl_master=GTL Masters
#role.code.master.menu.bkubk_master=BKUBK Masters
#role.code.master.menu.vtl_master=VTL Masters
#role.code.master.menu.tehbazari_master=Tehbazari Masters
#role.code.master.menu.csd_master=CSD Masters
#role.code.master.menu.eodbtwp_masters=EodbTwp Masters
#role.code.master.menu.eodbusr_masters=EodbUsr Masters
#role.code.master.menu.eodbobps_masters=EodbObps Masters
#role.code.master.menu.usercharge_masters=UserCharge Masters
#role.code.master.menu.adms_masters=Advertisement Masters
#role.code.master.menu.ruleEngine_masters=Rule Engine 
#role.code.master.menu.lems_masters=Lems Masters 
#role.code.master.menu.prms_masters=Prms Masters
#role.code.master.menu.htl_master=HTL Masters
#role.code.master.menu.signage_masters=SIGNAGE Masters
##HOTEL MOTEL
#role.code.master.menu.hmf_masters=Hotel Motel
#
#
##### Citizen Master Heading's inside master Code ###
#role.code.master.menu.citizen_master.MasterFooterRibbon=MasterFooterRibbon
#role.code.master.menu.citizen_master.MasterFooterMenu=MasterFooterMenu
#role.code.master.menu.citizen_master.MasterHeaderRibbon=MasterHeaderRibbon
#role.code.master.menu.citizen_master.MasterHelplineNumbers=MasterHelplineNumbers
#role.code.master.menu.citizen_master.MasterLogoDeptName=MasterLogoDeptName
#role.code.master.menu.citizen_master.MasterMenu=MasterMenu
#role.code.master.menu.citizen_master.MasterMenuObjectInfo=MasterMenuObjectInfo
#role.code.master.menu.citizen_master.MenuObjectContent=MenuObjectContent
#role.code.master.menu.citizen_master.MenuObjectDocument=MenuObjectDocument
#role.code.master.menu.citizen_master.MasterNoteMenu=MasterNoteMenu
#role.code.master.menu.citizen_master.MasterNotification=MasterNotification
#role.code.master.menu.citizen_master.MasterPhotoGallery=MasterPhotoGallery
#role.code.master.menu.citizen_master.MasterQuickLinks=MasterQuickLinks
#role.code.master.menu.citizen_master.MasterSocialLinks=MasterSocialLinks
#role.code.master.menu.citizen_master.MasterOfficerImageComment=MasterOfficerImageComment
#role.code.master.menu.citizen_master.MasterTextFlash=MasterTextFlash
#role.code.master.menu.citizen_master.masterFlashImage=masterFlashImage
#role.code.master.menu.citizen_master.MasterBgImage=MasterBgImage
#role.code.master.menu.citizen_master.MasterTenderDetails=MasterTenderDetails
#role.code.master.menu.citizen_master.WebInfoManager=WebInfoManager
#
#
#
