###### APPLICATION DATABASE PROPERTIES #####
### JNDI DATABASE PROPERTIES ##
#jndi.read.resource.url=java:/comp/env/jdbc/readDatabase
#jndi.read.write.resource.url=java:/comp/env/jdbc/readWriteDatabase
#
### READ DATABASE PROPERTIES ##
#jdbc.read.driver=org.postgresql.Driver
##jdbc.read.url=jdbc:postgresql://dbserver:5432/SDMC
##jdbc.read.url=jdbc:postgresql://10.194.162.125:5432/SDMC
##jdbc.read.url=jdbc:postgresql://10.197.214.29:5433/sdmc_swm
#jdbc.read.url=jdbc:postgresql://10.197.214.29:5432/SDMC
##jdbc.read.url=jdbc:postgresql://10.197.214.16:5433/SDMC_NEW
##jdbc.read.url=jdbc:postgresql://10.197.214.16:5433/SDMC_BETA
##jdbc.read.url=jdbc:postgresql://10.197.214.16:5432/MCSUITE_property
#
#jdbc.read.username=postgres
#jdbc.read.password=postgres
#
#
### READ-WRITE DATABASE PROPERTIES ##
#jdbc.read.write.driver=org.postgresql.Driver
##jdbc.read.write.url=jdbc:postgresql://dbserver:5432/SDMC
##jdbc.read.write.url=jdbc:postgresql://10.194.162.125:5432/SDMC
##jdbc.read.write.url=jdbc:postgresql://10.197.214.29:5433/sdmc_swm
#jdbc.read.write.url=jdbc:postgresql://10.197.214.29:5432/SDMC
##jdbc.read.write.url=jdbc:postgresql://10.197.214.16:5433/SDMC_NEW
##jdbc.read.write.url=jdbc:postgresql://10.197.214.16:5433/SDMC_BETA
##jdbc.read.write.url=jdbc:postgresql://10.197.214.16:5432/MCSUITE_property
#jdbc.read.write.username=postgres
#jdbc.read.write.password=postgres
#
#
### READ HIBERNATE PROPERTIES ##
#read.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
## <!-- AVAILABE OPTION FOR hbm2ddl.auto -- validate | update | create | create-drop -->
##read.hibernate.hbm2ddl.auto=validate
#read.hibernate.connection.release_mode=after_transaction
#read.hibernate.show_sql=false
#read.hibernate.format_sql=true
#read.hibernate.cache.use_second_level_cache=true
#read.hibernate.cache.use_query_cache=true
#read.hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
## <!-- Minimum number of JDBC connections in the pool. Hibernate default: 1 -->
#read.hibernate.c3p0.min_size=5
## <!-- Maximum number of JDBC connections in the pool. Hibernate default: 100 -->
#read.hibernate.c3p0.max_size=100
## <!-- When an idle connection is removed from the pool (in second). Hibernate default: 0, never expire. -->
#read.hibernate.c3p0.timeout=300
## <!-- Number of prepared statements will be cached. Increase performance. Hibernate default: 0 , caching is disable. -->
#read.hibernate.c3p0.max_statements=50
#read.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
#
### READ WRITE HIBERNATE PROPERTIES ##
#read.write.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
## <!-- AVAILABE OPTION FOR hbm2ddl.auto -- validate | update | create | create-drop -->
##read.write.hibernate.hbm2ddl.auto=validate
#read.write.hibernate.connection.release_mode=after_transaction
#read.write.hibernate.show_sql=true
#read.write.hibernate.format_sql=false
#read.write.hibernate.cache.use_second_level_cache=true
#read.write.hibernate.cache.use_query_cache=true
#read.write.hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
## <!-- Minimum number of JDBC connections in the pool. Hibernate default: 1 -->
#read.write.hibernate.c3p0.min_size=5
## <!-- Maximum number of JDBC connections in the pool. Hibernate default: 100 -->
#read.write.hibernate.c3p0.max_size=100
## <!-- When an idle connection is removed from the pool (in second). Hibernate default: 0, never expire. -->
#read.write.hibernate.c3p0.timeout=300
## <!-- Number of prepared statements will be cached. Increase performance. Hibernate default: 0 , caching is disable. -->
#read.write.hibernate.c3p0.max_statements=50
#read.write.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
#
#
### MONGO DB PROPERTIES ##
#mongodb.db.name=test
#mongodb.db.ip=localhost
#
#
### multiple database configuration ##
#hibernate.multiTenancy=DATABASE
#hibernate.tenant_identifier_resolver=app.pims.multiTenantConfig.CurrentTenantIdentifierResolverImpl
#hibernate.multi_tenant_connection_provider=app.pims.multiTenantConfig.MultiTenantConnectionProviderImpl
#
##pdf.system.path=/MCS/Japps/PDF
##pdf.system.path=/MCS/JApps/PDF
##pdf.system.path=/mcsdocs/sdmc/PDF
#pdf.system.path=D:/MasterPDF
##pdf.system.path1 = D:/vishal/videoPdf
